### ISSUE TITLE
"ERR_REQUIRE_ESM" when using native modules

### ISSUE THREAD

**Issue by luax** [heroku/heroku-nodejs-plugin#22]
Having an app running Node v14.3 and using [modules](https://nodejs.org/api/esm.html) by "type" set to "modules" in package.json seems to throw an error after enabling `runtime-heroku-metrics`:

```
app[web.2]: internal/modules/cjs/loader.js:1216
app[web.2]: throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
app[web.2]: ^
app[web.2]:
app[web.2]: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /app/.heroku/heroku-nodejs-plugin/index.js
app[web.2]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1216:13)
app[web.2]: at Module.load (internal/modules/cjs/loader.js:1049:32)
app[web.2]: at Function.Module._load (internal/modules/cjs/loader.js:937:14)
app[web.2]: at Module.require (internal/modules/cjs/loader.js:1089:19)
app[web.2]: at Module._preloadModules (internal/modules/cjs/loader.js:1345:12)
app[web.2]: at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
app[web.2]: at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
app[web.2]: at internal/main/run_main_module.js:7:1 {
app[web.2]: code: 'ERR_REQUIRE_ESM'
app[web.2]: }
```

The app crashes and cannot start due to:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /app/.heroku/heroku-nodejs-plugin/index.js
```

(Perhaps this should have been posted to [heroku-build-pack-nodejs](https://github.com/heroku/heroku-buildpack-nodejs/issues))

**Comment by danielleadams** [comment]
Hi @luax - this is the right place for this bug. I will investigate this and report back. It has to do with the plugin's use of `require` when ES Modules have been enabled. The plugin will need to do ES module-style imports when it's enabled, so I need to figure out what that looks like.

**Comment by luax** [comment]
Thanks @danielleadams! I also created a [support ticket](https://help.heroku.com/882087). 

Here is a reproducible example:

- `package.json`
  ```
  {
    "name": "heroku-test",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT",
    "type": "module",
    "engines": {
      "node": "14.x"
    },
    "dependencies": {
      "express": "4.17.1"
    }
  }
  ```

- `index.js`

  ```
  import express from 'express';

  const app = express()
  const port = process.env.PORT || 3000

  app.get('/', (req, res) => res.send('Hello World!'))

  app.listen(port, () => console.log(`Example app listening at http://localhost:${port}`))
  ```

**Comment by luax** [comment]
Sorry but are there any news on when this might be solved @danielleadams? 

My current workaround is booting with:
```
web: echo { \"type\": \"commonjs\" } > /app/.heroku/heroku-nodejs-plugin/package.json && node index.js
```

Or not use native modules as it seems risky to add things to `/app/.heroku` on the fly.

Thanks!

**Comment by danielleadams** [comment]
Hi @luax, this is on my list, but unfortunately haven't gotten around to it yet. For what it's worth, I would like to get this fixed as soon as possible since I think this is important to support, but since Node.js Language Metrics is a beta feature, it becomes a little harder to prioritize.

Nonetheless, I will keep this issue updated with my progress.

**Comment by imargulyan** [comment]
I face the same problem on a Hobby Dyno at Heroku. It is even more surprising that everything runs smoothly w/o any issues on a Free Dyno.  Node v14.5

**Comment by lblo** [comment]
Hi,
I'm also having the same issue after migrating my Node project to "type": "module" and killing all the _require_ in my project...
I'll try luax's solution.

**Comment by ahmadyousef1125** [comment]
Can confirm also.
When turning on this switch:
![image](https://user-images.githubusercontent.com/75946714/103708681-b2aa9580-4fb9-11eb-82e5-5fb641c866ef.png)

and setting "type": "module" in the package.json, then the app crashes with the mentioned error.

**Comment by danielleadams** [comment]
The fix will go out with the next release.
